# Generated by Django 2.2.3 on 2019-07-17 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TweetValidator', '0002_auto_20190717_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='%Y_%m_%d'),
        ),
    ]
