# Generated by Django 2.2.3 on 2019-07-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TruthSerum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='%Y/%m/%d'),
        ),
    ]
