# Generated by Django 2.2.3 on 2019-07-18 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TruthSerum', '0003_auto_20190717_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='description',
        ),
    ]
