# Generated by Django 2.2.3 on 2019-07-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TruthSerum', '0004_remove_document_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='%Y_%m_%d')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
