# Generated by Django 2.2.3 on 2019-07-19 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TruthSerum', '0004_remove_document_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='ImageUpload',
        ),
        migrations.RenameField(
            model_name='imageupload',
            old_name='document',
            new_name='file',
        ),
    ]
