# Generated by Django 2.2.3 on 2019-07-19 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TruthSerum', '0005_auto_20190719_0433'),
        ('TruthSerum', '0005_auto_20190719_0452'),
    ]

    operations = [
    ]
